#!/usr/bin/env python
#
# Original author Rob Kutschke.
#

import os, re
Import('env')

Import('mu2e_helper')

helper=mu2e_helper(env)

rootlibs  = env['ROOTLIBS']
babarlibs = env['BABARLIBS']

mainlib = helper.make_mainlib ( [ 
    'CLHEP',
    rootlibs,
    babarlibs,
    'canvas',
    'cetlib_except',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_Utilities',
    'mu2e_GlobalConstantsService',
    'mu2e_Mu2eInterfaces',
    'mu2e_Mu2eUtilities',
    'mu2e_BFieldGeom',
    'mu2e_DataProducts',
    'mu2e_MCDataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_CalorimeterGeom',
    'General',
    'Trajectory'
] )

# Fixme: split into link lists for each module.
helper.make_plugins( [
    mainlib,
    'art_Framework_Core',
    'art_Framework_Principal',
    'art_Framework_Services_Registry',
    'art_Utilities',
    'art_Persistency_Provenance',
    'art_root_io_TFileService',
    'art_root_io_tfile_support',
    'cetlib_except',
    'fhiclcpp',
    'fhiclcpp_types',
    'tbb',
    'canvas',
    rootlibs,
    'boost_filesystem',
    'mu2e_Mu2eInterfaces',
    'mu2e_DataProducts',
    'mu2e_RecoDataProducts',
    'mu2e_Mu2eUtilities',
    'mu2e_BFieldGeom',
    'mu2e_CRVAnalysis',
    'mu2e_TrkDiag'
    ] )

# Fixme: do I need all of babarlibs below?
helper.make_dict_and_map( [
        mainlib,
        'Core'
    ] )


# This tells emacs to view this file in python mode.
# Local Variables:
# mode:python
# End:
